### ISSUE TITLE
request: The possibility of caching data in seconds

### ISSUE THREAD

**Issue by KAJOOSH** [thiagoloureiro/EasyMemoryCache#8]
Hello
I have sensitive information that needs 30 seconds to be cached.
But this is not possible. In my opinion, you should reconsider the minute.

**Comment by thiagoloureiro** [comment]
Hi @KAJOOSH , i'll take a look into it.

**Comment by thiagoloureiro** [comment]
https://github.com/thiagoloureiro/EasyMemoryCache/pull/10 @KAJOOSH  @MarkCiliaVincenti 
what do you think guys?
The standard implementation doesn't change, minutes by default, but if you set interval manually then will be converted.

**Comment by KAJOOSH** [comment]
Do not be tired
Everything seems fine. But it should be checked after deployment in the project.

**Comment by thiagoloureiro** [comment]
I've tested with the sample projects worked fine. I'll run more checks and see if everything is fine.

**Comment by thiagoloureiro** [comment]
merged, will release new version soon.
